version: 2
jobs:
  build:
    working_directory: ~/transact_pro
    docker:           
      - image: circleci/ruby:2.1.10
      #- image: circleci/ruby@sha256:382aa3816e4a1447f56dfa5c70751a727eb276bb0d1617f1989e3ca28bb251f5
        timezone: "Europe/Riga"
        environment:
          USER_IP: "78.23.51.103"
      
    steps:
      - checkout
      
      - run: gem install bundler -v 1.16.0 --no-doc      

      - restore_cache:
         key: transact_pro-v1-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
         key: transact_pro-v1-{{ checksum "Gemfile.lock" }}
         paths:
           - vendor/bundle      

      - run: bundle exec rspec
