version: 2
jobs:
  build:
    working_directory: ~/transact_pro
    docker:           
      #- image: circleci/ruby:2.1.10      
      - image: circleci/ruby@sha256:e49f95920f6294593e99cd6401556a36a8b47703b5bdac0b094b66ae1cdd6569
        timezone: "Europe/Riga"
        environment:
          USER_IP: "78.23.51.103"
      
    steps:
      - checkout
      
      - run: gem install bundler -v 1.16.0 --no-doc      

      - restore_cache:
         key: transact_pro-v1-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle

      - save_cache:
         key: transact_pro-v1-{{ checksum "Gemfile.lock" }}
         paths:
           - vendor/bundle      

      - run: bundle exec rspec
